defaults:
  - trainer: default
  - logger: wandb
  - experiment: classic_l2
  - _self_

# General
seed: 42

dataset:
  _target_: __main__.MVTecDataModule
  root: data
  clase: cable
  batch_size: 32
  img_size: 128
  num_workers: 4
accelerator: "gpu"  # cambiar a "cpu" si no tienes GPU
devices: 1
precision: 16