defaults:
  - trainer: default
  - logger: wandb
  - experiment: unet_l2
  - loss: 12
  - _self_

# General
seed: 42

dataset:
  _target_: __main__.MVTecMultiClassDataModule
  root: data
  batch_size: 32
  img_size: 128
  num_workers: 4

accelerator: "auto"  # cambiar a "cpu" si no tienes GPU
